version: '3.7'
services:
  influx:
    image: influxdb:latest
    ports:
      - "8086:8086"
    restart: always
    network_mode: host

  app-server:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - influx