management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      influx:
        db: mydb
        enabled: true
        prefixes:
          custom: custom
          heap: heap
        uri: http://localhost:8086
